Kid.destroy_all()

rogue = Kid.create(name: "Rogue", nickname: "Pierogi", birthday: "2019-3-25")
kahlan = Kid.create(name: "Kahlan", nickname: "Bubba", birthday: "2011-6-24")
george = Kid.create(name: "George", nickname: "Buddy", birthday: "2013-8-19")
rocket = Kid.create(name: "Rocket", nickname: "Rocket, Rocket, Rocket", birthday: "2023-3-25")
Comment.create(kid: rogue, quoted: "2019-3-25", content: "Bless You Rescue")
Comment.create(kid: rogue, quoted: "2019-3-25", content: "no no no no no")
Comment.create(kid: rocket, quoted: "2019-3-25", content: "I Eat Toes")
Comment.create(kid: rocket, quoted: "2019-3-25", content: "Woff Woff")
Comment.create(kid: george, quoted: "2019-3-25", content: "Woff Woff Woff")
Comment.create(kid: george, quoted: "2019-3-25", content: "ahhhh durp")
Comment.create(kid: kahlan, quoted: "2019-3-25", content: "so yesterday")
Comment.create(kid: kahlan, quoted: "2019-3-25", content: "shiba do da")